### PR TITLE
rearrange decoded sql according to feature schema

### PR DESCRIPTION
**Pull request by azahnen**
I tested it with `gebaeude`, for these cases it works as expected.

### CODE REVIEW

**Comment by cportele** [comment]
@azahnen - I also did an initial test with LoD2 buildings in `gebaeude`, but I have encountered some problems. If I try to write GML I get exceptions, because at Object Start the schema has no `objectType` set. When I try to use GeoJSON I receive an exception, because a field name was written, but a value was expected. 

I have then turned on logging in the GML writer to see the sequence of the events (the event type and the name property of `context.schema()`). The following is a request for four buildings (without geometry details).  Look for the "..." comments which document unexpected behaviour. Am I doing something wrong, because it seems to have worked in your environment?

```
Feature Start: building
Value: id
Value: gml_id
Object Start: bbox
Object End: bbox
Object Start: lod12GroundSurface
Object End: lod12GroundSurface
Value: measuredHeight
Value: roofType
Value: creationDate
Value: function
Array Start: externalReferences
Object Start: externalReferences
Value: name
Value: informationSystem
Object End: externalReferences
Array End: externalReferences
Value: datenquelleBodenhoehe
Value: datenquelleDachhoehe
Value: datenquelleLage
Value: gemeindeschluessel
Array Start: address
Object Start: address
Value: ThoroughfareName
Value: ThoroughfareNumber
Value: LocalityName
Value: CountryName
Object End: address
Array End: address
... the schema name of the next object should be lod2Solid, not lod2MultiSurface:
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
... lod2MultiSurface is correct here:
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
... lod2TerrainIntersection is too early, it should be after the surfaces array:
Object Start: lod2TerrainIntersection
Object End: lod2TerrainIntersection
... for the surfaces there should be an Array Start and an Object Start, but we directly get a property:
Value: gml_id
Value: creationDate
Value: surfaceType
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
... here should be an Object End (for the surface) and an Object Start (for the next surface), but now we get the surfaces Array Start:
Array Start: surfaces
... now follows a sequence of surface objects, but all without Object Start and Object End for the surface object:
Value: gml_id
Value: creationDate
Value: surfaceType
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
Value: gml_id
Value: creationDate
Value: surfaceType
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
Value: gml_id
Value: creationDate
Value: surfaceType
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
Value: gml_id
Value: creationDate
Value: surfaceType
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
Value: gml_id
Value: creationDate
Value: surfaceType
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
Value: gml_id
Value: creationDate
Value: surfaceType
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
Value: gml_id
Value: creationDate
Value: surfaceType
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
Value: gml_id
Value: creationDate
Value: surfaceType
Object Start: lod2MultiSurface
Object End: lod2MultiSurface
... the Array End for the surfaces array that follows is correct:
Array End: surfaces
Object Start: lod2TerrainIntersection
... the lod2TerrainIntersection is at the right place here, but it is 'empty' (no arrays or properties) and the geometry has been sent already earlier
Object End: lod2TerrainIntersection
... the Feature End is correct in principle, but the schema is not:
Feature End: lod2TerrainIntersection
... same for the start of the next building feature, the schema is incorrect:
Feature Start: lod2TerrainIntersection
...
Feature End: lod2TerrainIntersection
Feature Start: lod2TerrainIntersection
...
Feature End: lod2TerrainIntersection
Feature Start: lod2TerrainIntersection
...
Feature End: lod2TerrainIntersection
```

**Comment by cportele** [comment]
I just see that the `gebaeude` configuration does not have the `lod2MultiSurface` property, this is just in my local configuration.

```yaml
      ...
      lod2Solid:
        label: Geometrie (LoD 2)
        sourcePath: lod2solid
        type: GEOMETRY
        geometryType: MULTI_POLYGON
        forcePolygonCCW: false
      lod2MultiSurface:
        label: Geometrie (LoD 2)
        sourcePath: lod2solid
        type: GEOMETRY
        geometryType: MULTI_POLYGON
        forcePolygonCCW: false
      ...
```

**Comment by azahnen** [comment]
@cportele Sorry, I only tested with lod1. Please try again.

**Comment by cportele** [comment]
@azahnen - Testing with challenging configurations is always good :). 

The weird thing is that now I get an "Comparison method violates its general contract!" exception from sorting paths using `FeatureStorePathParserSql.sortByPriority` during  `createTypeInfos()` in the feature provider startup for both lod1 and lod2. It does not appear that anything has changed in that part of the code. I need to see, if I can find out what is going on. 

I tried with another configuration (lod1 gebaeude from Hamburg) which did not have this startup issue. I still get at FeatureEnd and FeatureStart with `context.schema()` the schema of the last property, not of the feature.

**Comment by azahnen** [comment]
@cportele The error is indeed strange since I do not get it and you only get it with a specific configuration. I could only imagine that one of the values to be compared is null because of something unexpected you did in your configuration and that that triggers the exception. Apart from that I would expect a string comparison method to always work on a list of strings.

Regarding `onFeatureStart` and `onFeatureEnd`, I do not see that the sorting transformer changes the behavior. In `onFeatureStart` the path is set correctly, so you should get the correct schema. In `onFeatureEnd` the path is the one from the last property, but this behavior did not change, it was not introduced by the new transformer. Is that an issue for you?

**Comment by cportele** [comment]
@azahnen Yes, I also think the comparison issue must be something specific to my dev environment. I will have closer look in the next days (and maybe then the issue will be gone again by itself).

> Is that an issue for you?

Yes, because I need the schema of the feature in onFeatureStart to determine the GML object element tag. The behavior was different when I made the edits for the GML module. However, I have tested it again with the master branch of xtraplatform-spatial and indeed the behavior is the same as with the prop-order branch. That probably means that the behavior must have been the schema-scopes PR that introduced it?

**Comment by cportele** [comment]
I missed that you said that you see the correct schema in `onFeatureStart`. I get the wrong schema there. This is the issue, I don't think we use the schema currently anywhere in `onFeatureEnd`. So, the behavior in `onFeatureEnd` is not an issue.

I will try to make a clean build and see if that helps. If the behavior is correct on your machine and incorrect on mine and we are both using the same code...

**Review by cportele — APPROVED** [review]
The first issue is now gone. The second issue is still there, but this PR is unrelated. The order of the elements is now as expected. We can merge this PR.

**Comment by azahnen** [comment]
@cportele I logged after the sorting stage, where ´onFeatureStart´ looks correct. When logging before the encoding stage, I can confirm the issue. I will check what might have changed in recent PRs.

**Comment by cportele** [comment]
@azahnen - Thanks. I looked at the code and did some debugging - I really looks like there were no recent changes in FeatureTokenTransformerSchemaMappings where the change occurs (next transformer after the sorting transformer). This is strange, so I will also check, if anything changed in the GML code. But in any case, the context schema in `onFeaturesStart` should be the schema of the feature type.

**Pull request merged**
