### PR TITLE
SQL Queries For Nested CQL Filters

### PR DESCRIPTION
**Pull request by bekakh**
Closes interactive-instruments/ldproxy-project-management#43,

### CODE REVIEW

**Review by cportele — CHANGES_REQUESTED** [review]
I did an initial test. `theme[scheme='profile'].concept AEQUALS ['DLKM','Basis-DLM','DLM50']` did work, but the filter without the nested filter (`theme.concept AEQUALS ['DLKM','Basis-DLM','DLM50']`) now throws an NPE. Please fix this and check that the new changes do not invalidate any of existing filter expressions.

**Review by cportele — CHANGES_REQUESTED** [review]
I have also made tests with GeoVal and the position() function, but I am getting errors:

`filterValues[position() = 2].result_filterValueMeasurement BETWEEN 1 AND 5`

Error:

> Filter is invalid. Unknown property: %1$srow_number%2$s

`filterValues[position() IN (1,3)].result_filterValueMeasurement BETWEEN 1 AND 5`

Error:

> The parameter 'filter' is invalid: line 1:24 no viable alternative at input 'filterValues[position()IN'

Please also include unit tests for the SQL translation.

**Comment by cportele** [comment]
I just did a test with the geoinfodok API and the filter 

[theme[position()=1].concept ACONTAINS ['DLKM','Basis-DLM','DLM50']](http://localhost:7080/rest/services/geoinfodok/collections/ax_gebaeudefunktion/items?filter=theme%5Bposition()%3D1%5D.concept%20AContainS%20%5B%27DLKM%27%2C%20%27Basis-DLM%27%2C%20%27DLM50%27%5D)

which resulted in an `Unexpected SQL query error: column reference "id" is ambiguous`, because there is an "id" column from both "record" and "record_scheme" in the joined row.

**Comment by bekakh** [comment]
@cportele the problem should be fixed now.

**Comment by cportele** [comment]
@bekakh - Yes, the problem is fixed. 

The CI build still fails because of failing unit tests.

`de.ii.xtraplatform.cql.app.CqlTextSpec > Property with two nested filters FAILED; org.spockframework.runtime.SpockComparisonFailure at CqlTextSpec.groovy:626`

**Review by cportele — APPROVED** [review]

**Review by azahnen — APPROVED** [review]

**Pull request merged**
