### PR TITLE
Support temporal values in CQL comparison predicates

### PR DESCRIPTION
**Pull request by bekakh**
Add support for temporal values in CQL comparison predicates, as mentioned in https://github.com/interactive-instruments/ldproxy/issues/480. The supported predicates are:
- AFTER (>)
- BEFORE (<)
- TEQUALS (=)

### CODE REVIEW

**Comment by bekakh** [comment]
@cportele are there any other comparison predicates that should be included?

**Comment by cportele** [comment]
@bekakh - Yes, temporal properties and literals should also be supported for `<=`, `>=`, `<>`, `BETWEEN`, `IN`.

**Comment by azahnen** [comment]
@cportele Did you already review this? I would like to merge this before starting the implementation of self joins. I will review the code but you would have to assess if the requirements are met.

**Comment by cportele** [comment]
@azahnen - Not yet, I will do this today/tomorrow...

**Review by cportele — DISMISSED** [review]
I have tested all comparison operators with temporal values and the behaviour is as expected.

**Review by azahnen — APPROVED** [review]

**Pull request merged**
