### PR TITLE
fix removeSelect and reduceSelect

### PR DESCRIPTION
**Pull request by azahnen**
I think the original approach in `FeaturePropertyTransformerObjectRemoveSelect` was correct, the only bug was that it added the whole slice to the result and ignored start and end.
Apart from that there were some general issues in `FeaturePropertyTokenSliceTransformer` that also affected `objectReduceSelect`.
I also added some cases with `objectRemoveSelect` to the unit tests.

If this does not work you, I would need the specific use case.

### CODE REVIEW

**Comment by cportele** [comment]
@azahnen - Yes, that fixes the main issue and answers my question, if the changes should be done in `FeaturePropertyTokenSliceTransformer` as the handling of the concat/coalesce prefixes would also be relevant for other cases.

There is, however, one other issue that is not addressed by the changes. In  [FeaturePropertyTokenSliceTransformer.java#L424](https://github.com/interactive-instruments/xtraplatform-spatial/blob/fix-concat-coalesce-2/xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTokenSliceTransformer.java#L424), I think it should be `putIfAbsent`, not `put`, as with `put` the last non-NULL value is taken in coalesce, not the first, as it should be.

**Comment by azahnen** [comment]
@cportele That should theoretically not be an issue, since the transformers are called for a single object, not the whole array. I will have another look.

**Comment by cportele** [comment]
@azahnen - I did an artificial test, where I added a coalesce where the first option takes the id as the title and the second the name. The name is selected. If I swap both sub-properties, the id is used.

```yaml
      gehoertZuPlan:
        type: FEATURE_REF
        coalesce:
        - type: FEATURE_REF
          properties:
            id:
              sourcePath: gehoertzuplan_pfs_plan_fk
              type: INTEGER
            title: 
              sourcePath: '[gehoertzuplan_pfs_plan_fk=_id]pfs_plan/_id'
              type: STRING
            type:
              constantValue: pfs_plan
              type: STRING
        - type: FEATURE_REF
          properties:
            id:
              sourcePath: gehoertzuplan_pfs_plan_fk
              type: INTEGER
            title: 
              sourcePath: '[gehoertzuplan_pfs_plan_fk=_id]pfs_plan/name'
              type: STRING
            type:
              constantValue: pfs_plan
              type: STRING
```

**Comment by cportele** [comment]
@azahnen - That change does not impact the case when the coalesce value is a (FEATURE_REF) object. 

In that case and with the configuration, the slice is a single object with six properties - twice each `gehoertZuPlan.id` (both `1`), `gehoertZuPlan.type` (both `"pfs_plan"`), and `gehoertZuPlan.title` (`"1"` and `"(the name)"` ). The last value for title then wins. There is no selection of the first non-Null object, because there is a single object with the properties from all variants. 

I am not sure though, if that is and issue in practice. The example is artificial and I used it to test the behavior, but this is not something that would be used in practice. So maybe this is a non-issue?

**Comment by cportele** [comment]
@azahnen - The changes do not affect the flow in my example. I pushed the configuration to `xleit`, branch `xtrasse_PFS_2_gas`. Request: `http://localhost:7080/rest/services/xtrasse_PFS_2_gas/collections/bst_speicher/items/1?f=json`. The coalesced property is `gehoertZuPlan`. Could you have a look at that case? Thanks.

**Comment by azahnen** [comment]
@cportele Thanks for the configuration, there are still some issues I am going to fix.

But apart from the implementation issues there is also a design issue, which brings us back to the question if this is a case we need/want to support. 
The `coalesce` transformer is always executed first, so any other transformers will only see the first non-null object (when the implementation issues are fixed). That means the `objectRemoveSelect` transformer can only decide if the given object is removed or not, but a removal will not lead to the next non-null object from the coalesce being returned.
If that is a required use case, we would need some way to tell the coalesce transformer that an object should only be deemed non-null when a given property is non-null.

**Comment by cportele** [comment]
@azahnen 

Good point about the sequence of the transformers - and whether we want to support such a case. I am sure there are real-world use cases for such a scenario, but we can also wait with supporting them until there is a concrete need. We should just add limitations to the documentation.

> If that is a required use case, we would need some way to tell the coalesce transformer that an object should only be deemed non-null when a given property is non-null.

One possibility would be the `required` constraint of the properties. Any object where a required property is `null` would be mapped to `null`. 

While thinking about where this is a real-world scenario that we should support, I came up with a different configuration for the scenario:

```yaml
      gehoertZuPlan:
        type: FEATURE_REF
        properties:
          id:
            sourcePath: gehoertzuplan_pfs_plan_fk
            type: INTEGER
          title: 
            type: STRING
            coalesce:
            - sourcePath: '[gehoertzuplan_pfs_plan_fk=_id]pfs_plan/name'
            - sourcePath: '[gehoertzuplan_pfs_plan_fk=_id]pfs_plan/nummer'
            - sourcePath: '[gehoertzuplan_pfs_plan_fk=_id]pfs_plan/_id'
          type:
            constantValue: pfs_plan
            type: STRING
```

This is a use case that I see, often a label property is not required, so there is a need for one or more fallbacks. 

I pushed this change to the branch. This also does not work, because the FEATURE_REF object is processed before the coalesce property. All coalesce values are present when processing `gehoertZuPlan` and the last value (`_id`) "wins" when processing the FEATURE_REF object. That is, when `gehoertZuPlan.title` is processed, the title has already been set.

I don't think there is an easy way to change this, so probably we should also add to the documentation that coalesce cannot be used for FEATURE_REF properties.

**Comment by azahnen** [comment]
@cportele The first case should work now.

> One possibility would be the `required` constraint of the properties. Any object where a required property is `null` would be mapped to `null`.

That would indeed be an elegant solution and also easy to implement, I added a TODO to the coalesce transformer for now.

> I don't think there is an easy way to change this, so probably we should also add to the documentation that coalesce (or any property transformation) cannot be used for FEATURE_REF properties.

It could be sufficient to execute transformations for longer paths first, but I agree that this needs more thought. A hint in the docs should be enough for now

**Pull request merged**
