### PR TITLE
Multi queries

### PR DESCRIPTION
**Pull request by azahnen**
**Example**

```java
if (featureProvider.supportsMultiQueries()) {
  MultiFeatureQuery multiFeatureQuery = ImmutableMultiFeatureQuery.builder()
      .limit(10)
      .addQueries(ImmutableSubQuery.builder()
          .type("AeronauticSrf")
          .build())
      .addQueries(ImmutableSubQuery.builder()
          .type("CultureSrf")
          .build())
      .build();
  FeatureStream featureStream = featureProvider.multiQueries().getFeatureStream(multiFeatureQuery);
}
```

### CODE REVIEW

**Comment by azahnen** [comment]
@cportele I have only tested a small subset of cases as of now.
It would also be good to run some of the e2e tests to make sure that standard queries still work as expected.

**Comment by cportele** [comment]
@azahnen - I will run the tests.

**Comment by cportele** [comment]
@azahnen - The e2e tests pass, both with FeatureQuery and with MultiFeatureQuery with a single sub-query.

I will do more testing with multiple sub-queries today.

**Comment by cportele** [comment]
@azahnen - I have done a bit of testing with the daraa data. So far, I have only identified two issues:

The first one is that if I submit a query with two sub-queries the numberMatched value depends on whether the numberReturned is larger than the response from the first sub-query. If not, it just is the number of matches for the first sub-query. Otherwise it is the sum of the matches from both sub-queries. If that is not trivial, we could also skip numberMatched for the multi-collection queries. 

The second one: 

I use the following query:

```json
{
    "queries": [
        {
            "collections": [
                "CulturePnt"
            ],
            "sortby": ["-ZI001_SDV"],
            "properties": ["F_CODE", "ZI001_SDV", "ZI005_FNA"]
        },
        {
            "collections": [
                "RecreationPnt"
            ],
            "sortby": ["+ZI001_SDV"],
            "properties": ["F_CODE", "ZI001_SDV", "ZI005_FNA"]
        },
        {
            "collections": [
                "UtilityInfrastructurePnt"
            ],
            "sortby": ["ZI001_SDV"],
            "properties": ["F_CODE", "ZI001_SDV"]
        }
    ],
    "crs": "http://www.opengis.net/def/crs/EPSG/0/3857",
    "limit": 10,
    "offset": 1
}
```

This translates to the following `MultiFeatureQuery`:

```
MultiFeatureQuery{
    crs=EpsgCrs{
        code=3857, forceAxisOrder=NONE
    }, 
    maxAllowableOffset=0.0, 
    geometryPrecision=[2, 2], 
    limit=10, 
    offset=1, 
    queries=[
        SubQuery{
            type=CulturePnt, 
            sortKeys=[SortKey{field=ZI001_SDV, direction=DESCENDING}], 
            fields=[F_CODE, ZI001_SDV, ZI005_FNA], 
            skipGeometry=false
        }, 
        SubQuery{
            type=RecreationPnt, 
            sortKeys=[SortKey{field=ZI001_SDV, direction=ASCENDING}], 
            fields=[F_CODE, ZI001_SDV, ZI005_FNA], 
            skipGeometry=false
        }, 
        SubQuery{
            type=UtilityInfrastructurePnt, 
            sortKeys=[SortKey{field=ZI001_SDV, direction=ASCENDING}], 
            fields=[F_CODE, ZI001_SDV], 
            skipGeometry=false
        }
    ]
}
```

The result is attached (note: the code does not yet ensure that feature ids are unique). It says number returned is 10, but  it returns all features.

[out.json.zip](https://github.com/interactive-instruments/xtraplatform-spatial/files/9254016/out.json.zip)

**Comment by cportele** [comment]
@azahnen - Here is another problem after adding CQL2 filters.

The query:

```json
{
    "queries": [
        {
            "collections": ["CulturePnt"],
            "filter": {
                "op": "and",
                "args": [
                    {
                        "op": "<",
                        "args": [ {"property": "ZI001_SDV"}, "2012-07-01T00:00:00Z" ]
                    },
                    {
                        "op": "like",
                        "args": [ {"property": "F_CODE"}, "AL%" ]
                    }
                ]
            },
            "sortby": ["-ZI001_SDV"],
            "properties": ["F_CODE", "ZI001_SDV", "ZI005_FNA"]
        },
        {
            "collections": ["RecreationPnt"],
            "filter": {
                "op": "and",
                "args": [
                    {
                        "op": "<",
                        "args": [ {"property": "ZI001_SDV"}, "2012-07-01T00:00:00Z" ]
                    },
                    {
                        "op": ">",
                        "args": [ {"property": "F_CODE"}, "AK080" ]
                    }
                ]
            },
            "sortby": ["+ZI001_SDV"],
            "properties": ["F_CODE", "ZI001_SDV"]
        }
    ],
    "crs": "http://www.opengis.net/def/crs/EPSG/0/3857",
    "limit": 10,
    "offset": 0
}
```

Converted to this `MultiFeatureQuery`:

```
MultiFeatureQuery{
    crs=EpsgCrs{code=3857, forceAxisOrder=NONE}, 
    maxAllowableOffset=0.0, 
    geometryPrecision=[2, 2], 
    limit=10, 
    offset=0, 
    queries=[
        SubQuery{
            type=CulturePnt, 
            filter=And{args=[Lt{args=[Property{name=ZI001_SDV, nestedFilters={}, path=[ZI001_SDV]}, TemporalLiteral{type=class java.time.Instant, value=2012-07-01T00:00:00Z, date=Optional.empty, timestamp=Optional[2012-07-01T00:00:00Z], interval=Optional.empty}], op=<}, Like{args=[Property{name=F_CODE, nestedFilters={}, path=[F_CODE]}, ScalarLiteral{value=AL%, type=class java.lang.String}], op=like}], op=and}, 
            sortKeys=[SortKey{field=ZI001_SDV, direction=DESCENDING}], 
            fields=[F_CODE, ZI001_SDV, ZI005_FNA], skipGeometry=false
        }, 
        SubQuery{
            type=RecreationPnt, 
            filter=And{args=[Lt{args=[Property{name=ZI001_SDV, nestedFilters={}, path=[ZI001_SDV]}, TemporalLiteral{type=class java.time.Instant, value=2012-07-01T00:00:00Z, date=Optional.empty, timestamp=Optional[2012-07-01T00:00:00Z], interval=Optional.empty}], op=<}, Gt{args=[Property{name=F_CODE, nestedFilters={}, path=[F_CODE]}, ScalarLiteral{value=AK080, type=class java.lang.String}], op=>}], op=and}, 
            sortKeys=[SortKey{field=ZI001_SDV, direction=ASCENDING}], 
            fields=[F_CODE, ZI001_SDV], skipGeometry=false
        }
    ]
}
```

results in the following events in the stream (GeoJSON as output), `#` are comments added by me:

```
GeoJSON - Start  
GeoJSON - Feature Start: CulturePnt   
GeoJSON - Value: id = 5   
GeoJSON - Value: F_CODE = AL012   
GeoJSON - Object Start: geometry   
GeoJSON - Object End: geometry   
GeoJSON - Value: ZI001_SDV = 2012-03-27T11:53:13Z   
GeoJSON - Value: ZI005_FNA = Roman Graves   
GeoJSON - Feature End: CulturePnt   
GeoJSON - Feature Start: CulturePnt   
GeoJSON - Value: id = 1   
GeoJSON - Value: F_CODE = AL030   
GeoJSON - Object Start: geometry   
GeoJSON - Object End: geometry   
GeoJSON - Value: ZI001_SDV = 2011-12-27T18:39:59Z   
GeoJSON - Value: ZI005_FNA = مقبرة البحارة   
GeoJSON - Feature End: CulturePnt   
GeoJSON - Feature Start: CulturePnt   
GeoJSON - Value: id = 2   
GeoJSON - Value: F_CODE = AL130   
GeoJSON - Object Start: geometry   
GeoJSON - Object End: geometry   
GeoJSON - Value: ZI001_SDV = 2011-12-26T20:55:27Z   
GeoJSON - Value: ZI005_FNA = ساحة الكرامة   
# Here should be Feature End and then Feature Start of the first RecreationPnt feature
GeoJSON - Value: id = 2   
GeoJSON - Value: F_CODE = AK180   
GeoJSON - Object Start: geometry   
GeoJSON - Object End: geometry   
GeoJSON - Value: ZI001_SDV = 2011-12-09T21:34:51Z   
# ZI005_FNA is not included in fields for this feature type
GeoJSON - Value: ZI005_FNA = حديقة الحيونات   
# This should be the end of the first RecreationPnt feature
GeoJSON - Feature End: CulturePnt   
GeoJSON - Feature Start: RecreationPnt   
# This triggers an exception:
Can not start an object, expecting field name (context: Object)
```

**Comment by azahnen** [comment]
@cportele Thanks for the tests, I will look into the issues today.

**Comment by azahnen** [comment]
@cportele Please try again, the examples should work now.
I couldn't see an issue with numberMatched, if it still occurs for you, please provide an example.
Not sure if that is clear, but to get unique ids, you would have to pass property transformations that apply the collection prefix.

**Comment by cportele** [comment]
Thanks @azahnen 

> I couldn't see an issue with numberMatched, if it still occurs for you, please provide an example.

OK, I will try to see, if I can reproduce the behavior. It is also not a blocker, if it is still there.

> Not sure if that is clear, but to get unique ids, you would have to pass property transformations that apply the collection prefix.

Yes, thanks, that is one of the items on the todo list.

**Comment by cportele** [comment]
> I couldn't see an issue with numberMatched, if it still occurs for you, please provide an example.

Here is one with three collections:

```
curl -X POST "https://t18.ldproxy.net/d103_airports/search" -H  "accept: application/geo+json" -H  "Content-Type: application/json" -d "{\"title\":\"Concrete apron, runway and taxiway elements at NYC area airports\",\"queries\":[{\"collections\":[\"apronelement\"],\"sortby\":[\"airport\"]},{\"collections\":[\"runwayelement\"],\"sortby\":[\"airport\"]},{\"collections\":[\"taxiwayelement\"],\"sortby\":[\"airport\"]}],\"filter\":{\"op\":\"and\",\"args\":[{\"op\":\"=\",\"args\":[{\"property\":\"composition\"},\"CONC\"]},{\"op\":\"in\",\"args\":[{\"property\":\"airport\"},[\"JFK\",\"EWR\",\"LGA\"]]}]},\"filterOperator\":\"AND\",\"properties\":[\"geometry\",\"airport\",\"type\"],\"limit\":1000}"
```

With limit=1000:

- "numberReturned": 1000
- "numberMatched": 1294

With limit=100:

- "numberReturned": 100
- "numberMatched": 138

With limit=10:

- "numberReturned": 10
- "numberMatched": 58

**Review by cportele — APPROVED** [review]
numberMatched now works as expected. I think we should merge this now into master.

**Comment by azahnen** [comment]
@cportele We have to merge this together with interactive-instruments/ldproxy#705 since I made a small change to the `FeatureStream` interface. Alternatively, we could create a new branch in ldproxy and cherry-pick the needed commits.

**Comment by cportele** [comment]
@azahnen - Ah ok, I will have a look, what needs to/should be done to merge the ldproxy PR into master, too. If it is too much for now, I will create a new branch with the relevant commits/changes.

**Comment by cportele** [comment]
@azahnen - I am adding paging and found another issue. I am using the same query as above, but this time with offset. `numberMatched` is 1294, which is correct (there are 58 apronelement, 80 runwayelement and 1156 taxiwayelement). However, when I use offset, the response is empty, if offset is 1156 (the number of taxiway elements) or larger.

As an aside: For testing I have switched on logging of the SQL queries and results. I noticed that the queries are executed immediately, but it sometimes took 10s or more until the response was sent. I will look at this more closely and see, if I can find out more information and how to reproduce the behaviour.

```
% curl -X POST "https://t18.ldproxy.net/d103_airports/search" -H  "accept: */*" -H  "Content-Type: application/json" -d "{\"id\":\"nyc-concrete-surface-areas\",\"title\":\"Concrete apron, runway and taxiway elements at NYC area airports\",\"queries\":[{\"collections\":[\"apronelement\"],\"sortby\":[\"airport\"]},{\"collections\":[\"runwayelement\"],\"sortby\":[\"airport\"]},{\"collections\":[\"taxiwayelement\"],\"sortby\":[\"airport\"]}],\"filter\":{\"op\":\"and\",\"args\":[{\"op\":\"=\",\"args\":[{\"property\":\"composition\"},\"CONC\"]},{\"op\":\"in\",\"args\":[{\"property\":\"airport\"},[\"JFK\",\"EWR\",\"LGA\"]]}]},\"properties\":[\"geometry\",\"airport\",\"type\"],\"limit\":1,\"offset\":1155}" 

{"type":"FeatureCollection","numberReturned":1,"numberMatched":1294,"timeStamp":"2022-09-07T05:03:42Z","features":[{"type":"Feature","id":"taxiwayelement.9180","geometry":{"type":"Polygon","coordinates":[removed]},"properties":{"airport":"LGA","type":"NORMAL"}}]}

% curl -X POST "https://t18.ldproxy.net/d103_airports/search" -H  "accept: */*" -H  "Content-Type: application/json" -d "{\"id\":\"nyc-concrete-surface-areas\",\"title\":\"Concrete apron, runway and taxiway elements at NYC area airports\",\"queries\":[{\"collections\":[\"apronelement\"],\"sortby\":[\"airport\"]},{\"collections\":[\"runwayelement\"],\"sortby\":[\"airport\"]},{\"collections\":[\"taxiwayelement\"],\"sortby\":[\"airport\"]}],\"filter\":{\"op\":\"and\",\"args\":[{\"op\":\"=\",\"args\":[{\"property\":\"composition\"},\"CONC\"]},{\"op\":\"in\",\"args\":[{\"property\":\"airport\"},[\"JFK\",\"EWR\",\"LGA\"]]}]},\"properties\":[\"geometry\",\"airport\",\"type\"],\"limit\":1,\"offset\":1156}" 

{"type":"FeatureCollection","numberReturned":1,"numberMatched":1294,"timeStamp":"2022-09-07T05:03:57Z","features":[]}
```

**Comment by azahnen** [comment]
I implemented a fix in #143 and applied it to interactive-instruments/ldproxy#705. Let me know if there is still an issue.

Regarding the slowness, the query below takes very long, which might be improved by adding indexes. It is much faster without custom sort key. 
Because it returns zero rows, there is no way to see in the log that it is still running. I improved the logging to address that.

```sql
SELECT A.airport AS CSKEY_0, A.ogc_fid AS SKEY, B.ogc_fid AS SKEY_1, B.designator, B.ogc_fid FROM taxiwayelement A JOIN taxiway B ON (A.associatedtaxiway=B.gml_id) WHERE (A.ogc_fid IN (SELECT AAA.ogc_fid FROM taxiwayelement AAA WHERE ((AAA.ogc_fid IN (SELECT AA.ogc_fid FROM taxiwayelement AA WHERE AA.composition = 'CONC') AND A.ogc_fid IN (SELECT AA.ogc_fid FROM taxiwayelement AA WHERE AA.airport IN ('JFK','EWR','LGA')))) ORDER BY AAA.airport,AAA.ogc_fid LIMIT 1 OFFSET 1017)) ORDER BY 1,2,3
```

**Comment by azahnen** [comment]
@cportele See above.

**Pull request merged**
